Re-organise skiboot code from libstb
open-power/secvarctl pull request #14
Opened 2021-05-05 03:12 UTC by daxtens

Lay out the libstb code in the same way it's laid out in skiboot.

This should make everything else more straightforward later.

Signed-off-by: Daniel Axtens <dja@axtens.net>

2021-05-05 21:25 UTC, nick-child-ibm requested changes
Noticed a few things. Mainly the build is failing, the notes I left should resolve this. There were also some issues during `make clean` since you added a deeper path, some of the coverage files would not delete. I recommend going into the Makefile and removing a deeper level of the coverage files with something like :
`	rm -f ./*/*/*/*/*/*.cov.* ./*/*/*/*/*.cov.* ./*/*.cov.* secvarctl-cov ./*.cov.* ./backends/*/*.cov.* ./external/*/*.cov.* ./html*
`


I would also recommend including the separation `secvar.h` into two `secvar.h` files in this PR. To refresh, when getting this project started, skiboot had two files called `secvar.h` that I needed to include. One was from skiboot `include/` and the other `libstb/secvar/`. Now that we are including more of skiboot and we have these two directories available to use, we should probably split `secvar.h` to two files, there are details in secvarctls current `secvar.h`'s comments on what code is from which `secvar.h`.

As I am writing this I am realizing there are further issues with `make clean` since some of the object files that were built are only added with conditionals on flags from the `make` command, of course `make clean` does not and should not accept flags like the build command so `rm -f $(OBJ)` will not remove the same `$(OBJ)` that was used during build. To be more specific, `crypto-openssl.o` only gets built with the `make OPENSSL=1` command, when we run `make clean` it does not delete this file since it is never added the list of object files without the `OPENSSL=1` flag. I could easily do some workaround but I am starting to dream of an easier way to just recursively delete all build files. Anyways, sorry for word dump I am thinking out loud and will post a PR soon to fix our increasingly gross cleanup. If you have any suggestions let me know. 

As always thanks for all your help and time with working on secvarctl. It is greatly appreciated.

2021-05-05 21:39 UTC, nick-child-ibm commented
Also, not sure how closely you are trying to mirror skiboot yet but files `container_of.h` , `check_type.h` , `list.h` all live in their own sub-directory inside of the `ccan` directory in Skiboot.

2021-05-07 01:48 UTC, daxtens commented on external/skiboot/libstb/secvar/backend/edk2.h
> +#include "external/skiboot/include/short_types.h" //added by Nick Child, dja
Thanks, I've added another commit which I think will help.

2021-05-07 01:49 UTC, daxtens commented
> Also, not sure how closely you are trying to mirror skiboot yet but files `container_of.h` , `check_type.h` , `list.h` all live in their own sub-directory inside of the `ccan` directory in Skiboot.

Ah, good spot.

2021-05-07 01:50 UTC, daxtens commented on backends/edk2-compat/edk2-svc-generate.c
> +#include "external/skiboot/libstb/secvar/backend/edk2-compat-process.h" // work on factoring this out
Consistency with the existing code. I haven't developed a grand theory about which includes should use `"..."` and which should use `<...>` just yet.

2021-05-07 02:15 UTC, daxtens commented
> Noticed a few things. Mainly the build is failing, the notes I left should resolve this. There were also some issues during `make clean` since you added a deeper path, some of the coverage files would not delete. I recommend going into the Makefile and removing a deeper level of the coverage files with something like :
> ` rm -f ./*/*/*/*/*/*.cov.* ./*/*/*/*/*.cov.* ./*/*.cov.* secvarctl-cov ./*.cov.* ./backends/*/*.cov.* ./external/*/*.cov.* ./html* `

I have a patch now that uses a bigger hammer. See what you think.

> 
> I would also recommend including the separation `secvar.h` into two `secvar.h` files in this PR. To refresh, when getting this project started, skiboot had two files called `secvar.h` that I needed to include. One was from skiboot `include/` and the other `libstb/secvar/`. Now that we are including more of skiboot and we have these two directories available to use, we should probably split `secvar.h` to two files, there are details in secvarctls current `secvar.h`'s comments on what code is from which `secvar.h`.

Done.

2021-05-07 17:44 UTC, nick-child-ibm approved these changes
Everything compiles and cleans beautifully. LGTM

2021-05-07 17:44 UTC, nick-child-ibm commented on Makefile
> +	find . -name "*.cov.*" -delete
`find` is included in distros right? I refuse to put it in package requirements hehehe

2021-05-07 17:44 UTC, nick-child-ibm commented on Makefile
> +	find . -name "*.cov.*" -delete
Regardless, this is the one-stop-cleanup-shop command I was looking for. Thanks!

2021-05-10 00:54 UTC, daxtens commented on external/skiboot/libstb/secvar/secvar_util.c
> +#include "secvar.h"
I am fairly sure a `"..."` include will look at the current directory first. So this should pick up `external/skiboot/libstb/secvar/secvar.h`. That's what `secvar_util.c` does in the Skiboot source: https://github.com/open-power/skiboot/blob/master/libstb/secvar/secvar_util.c#L12

2021-05-10 00:56 UTC, merged